{-# OPTIONS --cubical --erasure --guardedness #-}
module BrouwerTree.OrdinalDecidability.index where

import BrouwerTree.OrdinalDecidability.Basic
import BrouwerTree.OrdinalDecidability.CountableChoice
import BrouwerTree.OrdinalDecidability.GeneralProperties
import BrouwerTree.OrdinalDecidability.LPOMinMax
import BrouwerTree.OrdinalDecidability.MaxFunctionRel
import BrouwerTree.OrdinalDecidability.MinFunctionRel
import BrouwerTree.OrdinalDecidability.Paper
import BrouwerTree.OrdinalDecidability.QuantificationConstruction
import BrouwerTree.OrdinalDecidability.QuantificationCut
import BrouwerTree.OrdinalDecidability.QuantificationLemmas
import BrouwerTree.OrdinalDecidability.QuantificationTheorem
import BrouwerTree.OrdinalDecidability.Sierpinski
import BrouwerTree.OrdinalDecidability.SierpinskiBelowOmegaSquared
